### ISSUE TITLE
Submit Podspec to trunk

### ISSUE THREAD

**Issue by marcelofabri** [glenyi/FloatRatingView#10]
It'd be easier to people find out about (and use) FloatRatingView if the Podspec was pushed to CocoaPods Spec repo.

More info: https://guides.cocoapods.org/making/getting-setup-with-trunk.html

**Comment by SRandazzo** [comment]
bump! this would very helpful

**Comment by mkalmes** [comment]
*bump*
Please push the spec to the CocoaPods repo. I'm happy to help you with this, if you need help maintaining the pod.

**Comment by glenyi** [comment]
This is finally in. Better late than never!
