### ISSUE TITLE
Integration with RxSwift

### ISSUE THREAD

**Issue by mfarees** [glenyi/FloatRatingView#27]
How can I integrate this with an RxSwift project? I am trying to bind the FloatViewRating.rating value to an RxSwift variable in the model.

**Comment by glennposadas** [comment]
You can just make an Rx extension for the rating property of the FRV. :)

**Comment by glennposadas** [comment]
Here:

> import UIKit
import RxSwift
import RxCocoa

public extension Reactive where Base: FloatRatingView {
    
    /// Bindable sink for `rating` property
    public var backgroundColor: Binder<Double?> {
        return Binder(self.base) { frv, attr in
            frv.rating = attr ?? 0
        }
    }
}
