### ISSUE TITLE
... not key value coding-compliant for the key ...

### ISSUE THREAD

**Issue by sebbu** [glenyi/FloatRatingView#3]
I am getting a bunch of warnings of the following type:

Ignoring user defined runtime attribute for key path [variable name] of instance of UIView. Hit an exception when attempting to set its value ...setValue:forUndefinedKey:  this class is not key value coding compliant for the key [variable name]

I see this for editable, emptyImage, floatRatings, fullImage, halfRatings and so on.

I have inserted a view controller to storyboard which has a view with custom class FloatRatingView.

I believe that I started to see it after changing the deployment target to iOS7. I have already searched the web, but I did not find a fast solution. I am happy to help if I understand the issue.

**Comment by kangddong** [comment]
감사합니다
