### ISSUE TITLE
No support for RTL

### ISSUE THREAD

**Issue by pooja816** [glenyi/FloatRatingView#30]
My app is in Arabic but the ratingview is still in LTR. Please help me asap how can I solve this problem.

**Comment by fparkar** [comment]
I have updated code that works for arabic app too...

    // Calculates new rating based on touch location in view
    private func updateLocation(_ touch: UITouch) {
        guard editable else {
            return
        }

        let touchLocation = touch.location(in: self)
        var newRating: Double = 0
        
        var from1:Int = 0
        var through1:Int = maxRating-1
        var factorForCalculation:Int = +1
        
        if (GlobalFunctions.isEnglishApp()) {
            from1 = maxRating-1
            through1 = 0
            factorForCalculation = -1
        }
        
        //         for i in stride(from: (maxRating-1), through: 0, by: -1) { // -- english
        // for i in stride(from: 0, through: (maxRating-1), by: +1) { //-- arabic
            
        for i in stride(from: from1, through: through1, by: factorForCalculation) {
            let imageView = emptyImageViews[i]
            guard touchLocation.x > imageView.frame.origin.x else {
                continue
            }
            // Find touch point in image view
            let newLocation = imageView.convert(touchLocation, from: self)

            // Find decimal value for float or half rating
            if imageView.point(inside: newLocation, with: nil) && (type.supportsFractions()) {
                let decimalNum = Double(newLocation.x / imageView.frame.size.width)
                newRating = Double(i) + decimalNum
                if type == .halfRatings {
                    newRating = Double(i) + (decimalNum > 0.75 ? 1 : (decimalNum > 0.25 ? 0.5 : 0))
                }
            } else {
                // Whole rating
                newRating = Double(i) + 1.0
            }
            break
        }

        // Check min rating
        rating = newRating < Double(minRating) ? Double(minRating) : newRating

        // Update delegate
        delegate?.floatRatingView?(self, isUpdating: rating)
    }


    // MARK: UIView
    
    // Override to calculate ImageView frames
    override open func layoutSubviews() {
        super.layoutSubviews()

        guard let emptyImage = emptyImage else {
            return
        }

        let desiredImageWidth = frame.size.width / CGFloat(emptyImageViews.count)
        let maxImageWidth = max(minImageSize.width, desiredImageWidth)
        let maxImageHeight = max(minImageSize.height, frame.size.height)
        let imageViewSize = sizeForImage(emptyImage, inSize: CGSize(width: maxImageWidth, height: maxImageHeight))
        let imageXOffset = (frame.size.width - (imageViewSize.width * CGFloat(emptyImageViews.count))) /
                            CGFloat((emptyImageViews.count - 1))
        
        
        for i in 0..<maxRating {
            var imageFrame = CGRect(x: i == (maxRating-1) ? 0 : CGFloat(4-i)*(imageXOffset+imageViewSize.width), y: 0, width: imageViewSize.width, height: imageViewSize.height)
            
            if (GlobalFunctions.isEnglishApp()) {
                imageFrame = CGRect(x: i == 0 ? 0 : CGFloat(i)*(imageXOffset+imageViewSize.width), y: 0, width: imageViewSize.width, height: imageViewSize.height)
            }
            
            var imageView = emptyImageViews[i]
            imageView.frame = imageFrame
            
            imageView = fullImageViews[i]
            imageView.frame = imageFrame
        }
        
        
        refresh()
    }

Changes are done where I have added `GlobalFunctions.isEnglishApp()` which return true if I am using english app. Search for `GlobalFunctions.isEnglishApp`

Only updated changes are at 2 places.

**Comment by mubasherkhan** [comment]
@fparkar  your solution is working fine when stars are full.But there is a issue when stars are half.See the attached image.
<img width="126" alt="screen shot 2018-09-06 at 2 59 23 pm" src="https://user-images.githubusercontent.com/11816744/45150594-9ded4580-b1e5-11e8-962b-0886afc07666.png">
